# svs/lang/es.ini
[language]
name = es

[types]
vowel       = a e i o u
nasal       = m n ng ny
trill       = rr
fricative   = bh dh gh s sh f x
approximant = w y l
aspirate    = br h hy
plosive     = b d g p t r k ch
silence     = sil gs cl

[voiced]          # exceptions to per-type defaults
yes = b d g r 
no  =

[steady]          # exceptions; default steady = vowel + nasal
yes =
no  =